version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Rn.Common/Rn.Common.csproj --verbosity m
build_script:
  # output will be in /.src/{YOUR_PROJECT_DIR}/bin/Debug/netcoreapp2.1/publish/
  - cmd: dotnet publish ./src/Rn.Common/Rn.Common.csproj
after_build:
  # For once the build has completed
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/Rn.CommonTests/Rn.CommonTests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd src/Rn.CommonTests
  - cmd: dotnet test
on_finish :
  # any cleanup in here